package main

import (
	"bufio"
	"fmt"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"
)

const (
	sourceURL = "https://www.iana.org/assignments/enterprise-numbers.txt"
	outFile   = "iana_numbers_generated.go"
)

type entry struct {
	ID  int
	Org string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	client := http.Client{Timeout: 120 * time.Second}

	req, err := http.NewRequest(http.MethodGet, sourceURL, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:148.0) Gecko/20100101 Firefox/148.0")

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to fetch iana numbers: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("failed to fetch iana numbers: bad status. status: %s", resp.Status)
	}

	scanner := bufio.NewScanner(resp.Body)

	var (
		currentID int
		org       string
	)

	db := map[int]string{}

	for scanner.Scan() {
		line := scanner.Text()

		if strings.HasPrefix(line, "    ") || strings.HasPrefix(line, "   ") {
			continue
		} else if strings.HasPrefix(line, "  ") && currentID != -1 {
			org = strings.TrimSpace(line)
			org = strings.Replace(org, "\"", "", -1)
			org = strings.Replace(org, "\\", "", -1)
			db[currentID] = org
		} else {
			currentID, err = strconv.Atoi(strings.TrimSpace(line))
			if err != nil {
				currentID = -1
				continue
			}
		}
	}

	if scanner.Err() != nil {
		return fmt.Errorf("failed to parse iana numbers: %w", scanner.Err())
	}

	list := make([]entry, 0, len(db))

	for k, v := range db {
		list = append(list, entry{k, v})
	}

	sort.Slice(list, func(i, j int) bool {
		return list[i].ID < list[j].ID
	})

	out, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer out.Close()

	err = template.Must(template.New("go").Parse(codeTemplate)).Execute(out, list)
	if err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	fmt.Printf("generated %s (%d entries)\n", outFile, len(list))

	return nil
}

const codeTemplate = `// Code generated by update_iana_numbers; DO NOT EDIT.

package main

var IANADB = map[uint32]string{
{{- range . }}
	{{ .ID }}: "{{ .Org }}",
{{- end }}
}
`
