package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
	"text/template"
)

const (
	sourceURL = "https://standards-oui.ieee.org/oui/oui.csv"
	outFile   = "oui_generated.go"
)

type entry struct {
	OUI string
	Org string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	client := http.Client{Timeout: 120 * time.Second}

	req, err := http.NewRequest(http.MethodGet, sourceURL, nil)
	if err != nil {
		return fmt.Errorf("failed to create new request: %w", err)
	}
	req.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:148.0) Gecko/20100101 Firefox/148.0")

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to fetch oui data: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("failed to fetch oui data: bad status. status: %s", resp.Status)
	}

	reader := csv.NewReader(resp.Body)

	header, err := reader.Read()
	if err != nil {
		return fmt.Errorf("failed to read oui data: %w", err)
	}

	var assignmentIdx, orgIdx = -1, -1

	for i, h := range header {
		switch h {
		case "Assignment":
			assignmentIdx = i
		case "Organization Name":
			orgIdx = i
		}
	}

	if assignmentIdx < 0 || orgIdx < 0 {
		return fmt.Errorf("failed to read oui data: columns not found")
	}

	seen := map[string]string{}

	for {
		row, err := reader.Read()

		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("failed to parse oui data: %w", err)
		}

		oui := strings.ToUpper(strings.TrimSpace(row[assignmentIdx]))
		org := strings.TrimSpace(row[orgIdx])

		if oui == "" || org == "" {
			continue
		}

		seen[oui] = strings.Replace(org, "\"", "", -1)
	}

	list := make([]entry, 0, len(seen))

	for k, v := range seen {
		list = append(list, entry{k, v})
	}

	sort.Slice(list, func(i, j int) bool {
		return list[i].OUI < list[j].OUI
	})

	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create oui file: %w", err)
	}
	defer f.Close()

	tmpl := template.Must(template.New("go").Parse(codeTemplate))

	err = tmpl.Execute(f, list)
	if err != nil {
		return fmt.Errorf("failed to execute oui template: %w", err)
	}

	fmt.Printf("generated %s (%d entries)\n", outFile, len(list))
	return nil
}

const codeTemplate = `// Code generated by update_oui; DO NOT EDIT.

package identify

var OUIDB = map[string]string{
{{- range . }}
	"{{ .OUI }}": "{{ .Org }}",
{{- end }}
}
`
